### PR TITLE
Ruby-School-book-Project.

### PR DESCRIPTION
**Pull request by CrystallineButterfly**
Hello there, 

⚫️ Thank you for reviewing this PR ❇️

⚫️ Task completed here = 

⚫️ Add Person, Student and Teacher classes ✅

⚫️ Decorate a class ✅

⚫️ Set up associations ✅

⚫️ Add Basic UI ✅ 

All the best- K 🤖

Side note: I have done these reviews on one PR due to time constraints, thank you for understanding 🙏

### CODE REVIEW

**Review by julie-ify — APPROVED** [review]
Hi @CrystallineButterfly,

## Highlights!
- Good feature branch name ✔️ 
- No linter errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 
- Good code organization and working app ✔️
- Descriptive README ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by RolandM99 — COMMENTED** [review]
Hi @CrystallineButterfly, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌

You have submitted a PR which is already been reviewed by another CR. I'll suggest you create a new `feature` branch for associations and then submit a PR request from that `feature` branch created into the `dev` branch.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Review by descholar-ceo — APPROVED** [review]
Hi @CrystallineButterfly 🤝 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
👍🏽 This PR follows the correct git flow ✔️ 
👍🏽 This PR does not have any linters error ✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by CrystallineButterfly** [comment]
Thank you very much to @julie-ify and @descholar-ceo and @RolandM99 Thank you also.

**Pull request merged**
